sudo: false
language: ruby
rvm:
  - 2.5.5
  - 2.6.2
  - ruby-head
branches:
  only:
    - master
cache: bundler
before_install:
  - travis_retry gem update --system
  - travis_retry gem install bundler
install:
  - travis_retry bundle install --jobs=3 --retry=3
notifications:
  email: false
