pid: tmp/pids/thin.pid
timeout: 60
wait: 60
log: log/thin.log
max_conns: 1024
require: []
environment: <%= ENV['SINATRA_ENV'] %>
max_persistent_conns: 1024
servers: 5
threaded: true
no-epoll: true
daemonize: true
chdir: /path/to/your/apps/root/sinatra
tag: a-name-to-show-up-in-ps aux
address: 0.0.0.0
port: 4000
threadpool_size: 20
